export const GET_GROUPS = "GET_GROUPS";
export const SET_GROUP = "SET_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

export const GET_PASSWORDS = "GET_PASSWORDS";
export const ADD_PASSWORD = "ADD_PASSWORD";
export const GET_PASSWORD = "GET_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const SET_PASSWORD = "SET_PASSWORD";
export const DELETE_PASSWORD = "DELETE_PASSWORD";

export const SET_USER = "SET_USER";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
